### ISSUE TITLE
Modelviews & QStandardItem

### ISSUE THREAD

**Issue by mfitzp** [jkennedy-usgs/sgp-gsadjust#66]
It's great we're using the model view approach to the data, however I wonder if things could be a little simpler if not using the QStandardItem?

In the model-view architecture you can define your own custom models which interpret requests for data and get them from a custom data source. Using this approach you can for example define a model that interfaces with your data in it's *native* form -- whether a hierarchy of dict/list or custom objects.

If I'm understanding the code correctly, currently we load the data + then iterate over it to popular the PyQt models. This step could be avoidable. As with the Simple models to go the other way (turn Qt models back into raw pickleable data).

Would you like me to have a look at implementing this? It's not straightforward, but think it could simplify things for you considerably.

**Comment by jkennedy-usgs** [comment]
Yes, this is a big one...originally in the development I forked another similar project that was maintaining native Python data (lists and dicts) and periodically synchronizing that with the PyQt objects. I did away with that and went to PyQt models only.

Personally, it seems like a big task to me, but if you think it's reasonable and an improvement I'd be willing to give it a try. Perhaps lets save that for a phase 2 of the review?

Possibly related, at one point I tried to implement the __iter__ and __next__ methods in the PyQt models to do:
for delta in roman_dg_model:
etc.

instead of
for i in range(roman_dg_model.rowCount()):
        delta = roman_dg_model.data(roman_dg_model.index(i, 0), role=QtCore.Qt.UserRole)

It mostly worked but there was a hangup and apparently I didn't take good notes.



________________________________

**Comment by mfitzp** [comment]
> Personally, it seems like a big task to me, but if you think it's reasonable and an improvement I'd be willing to give it a try. Perhaps lets save that for a phase 2 of the review?

Sure, it is a bit of work. There is another way thankfully -- making the QStandardItems act as transparent Python types a bit more, and handle their own type hierarchy -- which I'll focus on first.
